### ISSUE TITLE
Add support for new USB3 Logic16 products

### ISSUE THREAD

**Issue by madscientist159** [keesj/saleae-logic-libusb#2]
We have access to a Logic 16 and a wide variety of debug hardware-- what information do you need to start adding support?

Thanks!

**Comment by keesj** [comment]
Hello,

I don't know at this point I am assuming the fx2 chip is no longer used in the Logic 16 version,

perhaps watch http://thesignalpath.com/blogs/2011/05/31/saleae-logic-and-logic16-product-teardown/ and see what they say about that.

For my last project I found that https://sigrok.org/  (and sigrok-cli) where working well with the 8 channel version hence I don't plan spending much time on this project but would rather try to add support for the 16 bits version to sigrok ( bigger community)
